BosquesPaz/Controllers/FotosController.cs
using BosquesPaz.Models;
using BosquesPaz.Services;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BosquesPaz.Controllers
{
    /// <summary>
    /// Clase que responde a las acciones que solicitan las peticiones de entrada y salida. 
    /// </summary>
    /// <remarks>
    /// <h3>Calidad</h3>
    /// </hr>
    /// <b>Requerimiento: Help Desk</b></br>
    /// <b>Version: 1</b></br>
    /// <b>Autor: Grupo Cubo Ltda.</b></br>
    /// <b>Fecha: 19/12/2017<b></br>
    /// <b>Descripcion:</b> Funciona para visualizar las vistas de fotos, realizar peticiones a la capa de servicios y ejecutar acciones.
    /// </remarks>
    public class FotosController : Controller
    {
        /// <summary>
        /// Propiedad que instancia la clase FotosService
        /// </summary>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Propiedad que instancia el servicio FotosService, para enviar peticiones y recibir el resultado.
        /// </remarks>
        private FotosService Servicio
        {
            get
            {
                return new FotosService();
            }
        }

        /// <summary>
        /// Accion que guarda los datos de la vista fotos carga de fotos
        /// </summary>
        /// <param name="viewModel">Instancia de FotosBosques</param>
        /// <returns>Retorna redirecion a raiz</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Recibe una instancia de FotosBosques y la envia a la clase de servicio.
        /// </remarks>
        [HttpPost]
        public ActionResult UploadFotos(FotosBosques viewModel)
        {
            try
            {
                string route = ConfigurationManager.AppSettings["FotosFolder"];
                IList<FotosBosques> Fotos = new List<FotosBosques>();
                foreach (var file in viewModel.Fotos)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        FotosBosques foto = new FotosBosques();
                        string Url = route + Guid.NewGuid() + Path.GetExtension(file.FileName);
                        file.SaveAs(Url);
                        foto.Url = Url;
                        foto.Id_Bosque = viewModel.Id_Bosque;
                        foto.Descripcion = "Test";
                        Fotos.Add(foto);
                    }
                }
                Fotos = Servicio.GuardarFotosBosque(Fotos).ToList();
                return Redirect("/");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        /// <summary>
        /// Accion que carga la vista fotos visualizacion
        /// </summary>
        /// <param name="id">Identificador del bosque</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Retorna una vista parcial pasando como parametro una coleccion FotosBosques.
        /// </remarks>
        [HttpGet]
        public ActionResult VisualizarFotos(int? id)
        {
            IEnumerable<FotosBosques> Fotos = Servicio.ObtenerFotosBosque((int)id);
            return PartialView("FotosVisualizacion", Fotos);
        }

        [HttpGet]
        public ActionResult retonarFoto(int? id)
        {
            IEnumerable<FotosBosques> Fotos = Servicio.ObtenerFotosBosque((int)id);
            return PartialView("FotosVisualizacion", Fotos);
        }

        /// <summary>
        /// Accion que realiza la carga de la vista fotos carga de fotos
        /// </summary>
        /// <param name="id">Identificador del bosque</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Accion que realiza el retorno de la vista parcial fotos carga pasando como parametro una instancia de FotosBosques.
        /// </remarks>
        [HttpGet]
        public ActionResult LoadCargaFotos(int? id)
        {
            var model = new FotosBosques();
            model.Id_Bosque = (int)id;
            model.Fotos = new List<HttpPostedFileBase>();
            return PartialView("FotosCarga", model);
        }

        /// <summary>
        /// Accion que guarda los datos de la vista fotos carga individuos especies de fotos
        /// </summary>
        /// <param name="viewModel">Instancia de FotosIndividuosEspecies</param>
        /// <returns>Retorna redirecion al detalle de individuos/especies</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Recibe una instancia de FotosIndividuosEspecies y la envia a la clase de servicio.
        /// </remarks>
        [HttpPost]
        public ActionResult UploadFotosIndividuosEspecies(FotosIndividuosEspecies viewModel)
        {
            try
            {
                string route = ConfigurationManager.AppSettings["FotosFolder"];
                IList<FotosIndividuosEspecies> Fotos = new List<FotosIndividuosEspecies>();
                foreach (var file in viewModel.Fotos)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        FotosIndividuosEspecies foto = new FotosIndividuosEspecies();
                        string Url = route + Guid.NewGuid() + Path.GetExtension(file.FileName);
                        file.SaveAs(Url);
                        foto.Url = Url;
                        foto.Id_IndividuoEspecie = viewModel.Id_IndividuoEspecie;
                        foto.Descripcion = "Test";
                        Fotos.Add(foto);
                    }
                }
                Fotos = Servicio.GuardarIndividuosEspecies(Fotos).ToList();
                var id = Session["idBosque"];
                return Redirect("/?m=Bosques&id=" + Convert.ToInt16(id) + "&mb=Individuos&mbid=" + viewModel.Id_IndividuoEspecie);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        /// <summary>
        /// Accion que carga la vista fotos visualizacion individuos especies
        /// </summary>
        /// <param name="id">Identificador de individuos/especies</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Retorna una vista parcial pasando como parametro una coleccion FotosIndividuosEspecies.
        /// </remarks>
        [HttpGet]
        public ActionResult VisualizarFotosIndividuosEspecies(int? id)
        {
            IEnumerable<FotosIndividuosEspecies> Fotos = Servicio.ObtenerFotosIndividuoEspecie((int)id);
            return PartialView("FotosVisualizacionindividuosEspecies", Fotos);
        }

        /// <summary>
        /// Accion que realiza la carga de la vista fotos indiviudos especies carga de fotos
        /// </summary>
        /// <param name="id">Identificador de individuos/especies</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Accion que realiza el retorno de la vista parcial fotos carga pasando como parametro una instancia de FotosIndividuosEspecies.
        /// </remarks>
        [HttpGet]
        public ActionResult LoadCargaFotosIndividuosEspecies(int? id)
        {
            var model = new FotosIndividuosEspecies();
            model.Id_IndividuoEspecie = (int)id;
            model.Fotos = new List<HttpPostedFileBase>();
            return PartialView("FotosCargaIndividuosEspecies", model);
        }

        /// <summary>
        /// Accion que guarda los datos de la vista fotos carga productos servicios de fotos
        /// </summary>
        /// <param name="viewModel">Instancia de FotosProductosServicios</param>
        /// <returns>Retorna redirecion al detalle de productos/servicios</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Recibe una instancia de FotosProductosServicios y la envia a la clase de servicio.
        /// </remarks>
        [HttpPost]
        public ActionResult UploadFotosProductosServicios(FotosProductosServicios viewModel)
        {
            try
            {

BosquesPaz/Views/Fotos/FotosCarga.cshtml
@model BosquesPaz.Models.FotosBosques
@using BosquesPaz.Helpers
@using BosquesPaz.ServiceReferenceFuncionarios;

@{
    ///Realiza la instancia de la clase infraestructura para verificar los permisos del usuario
    var infraestructura = new Infraestructura();
    EntidadInfoUsuario info = null;
    if (Session["infoUsuario"] != null)
    {
        info = Session["infoUsuario"] as EntidadInfoUsuario;
    }
}

@using (Html.BeginForm("UploadFotos", "Fotos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    if (infraestructura.PermisoUsuario(info, "Crear", "Recursos"))
    {
        <div class="col-md-12">
            @Html.HiddenFor(m => m.Id_Bosque)
            @Html.LabelFor(m => m.Fotos)
        </div>
        <div class="col-md-12">
            <h5>Formatos aceptados(.jpg, .png, .jpeg, .gif, .tiff)</h5>
        </div>
        <div class="col-md-12">
            <input type="file" name="Fotos" id="Fotos" multiple accept=".jpg, .png, .jpeg, .gif, .tiff" />
        </div>
        <div class="col-md-12">
            <button class="btn btn-default">Guardar</button>
        </div>
    }
}

BosquesPaz/Views/Fotos/FotosCargaIndividuosEspecies.cshtml
@model BosquesPaz.Models.FotosIndividuosEspecies
@using BosquesPaz.Helpers
@using BosquesPaz.ServiceReferenceFuncionarios;

@{
    ///Realiza la instancia de la clase infraestructura para verificar los permisos del usuario
    var infraestructura = new Infraestructura();
    EntidadInfoUsuario info = null;
    if (Session["infoUsuario"] != null)
    {
        info = Session["infoUsuario"] as EntidadInfoUsuario;
    }
}

@using (Html.BeginForm("UploadFotosIndividuosEspecies", "Fotos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    if (infraestructura.PermisoUsuario(info, "Crear", "IndividuosEspecies"))
    {
        <div class="col-md-12">
            @Html.HiddenFor(m => m.Id_IndividuoEspecie)
            @Html.LabelFor(m => m.Fotos)
        </div>
        <div class="col-md-12">
            <h5>Formatos aceptados(.jpg, .png, .jpeg, .gif, .tiff)</h5>
        </div>
        <div class="col-md-12">
            <input type="file" name="Fotos" id="Fotos" multiple accept=".jpg, .png, .jpeg, .gif, .tiff" />
        </div>
        <div class="col-md-12">
            <button class="btn btn-default">Guardar</button>
        </div>
    }
}

BosquesPaz/Views/Fotos/FotosCargaProductosServicios.cshtml
@model BosquesPaz.Models.FotosProductosServicios
@using BosquesPaz.Helpers
@using BosquesPaz.ServiceReferenceFuncionarios;

@{
    ///Realiza la instancia de la clase infraestructura para verificar los permisos del usuario
    var infraestructura = new Infraestructura();
    EntidadInfoUsuario info = null;
    if (Session["infoUsuario"] != null)
    {
        info = Session["infoUsuario"] as EntidadInfoUsuario;
    }
}

@using (Html.BeginForm("UploadFotosProductosServicios", "Fotos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    if (infraestructura.PermisoUsuario(info, "Crear", "ProductosServicios"))
    {
        <div class="col-md-12">
            @Html.HiddenFor(m => m.Id_ProductoServicio)
            @Html.LabelFor(m => m.Fotos)
        </div>
        <div class="col-md-12">
            <h5>Formatos aceptados(.jpg, .png, .jpeg, .gif, .tiff)</h5>
        </div>
        <div class="col-md-12">
            <input type="file" name="Fotos" id="Fotos" multiple accept=".jpg, .png, .jpeg, .gif, .tiff" />
        </div>
        <div class="col-md-12">
            <button class="btn btn-default">Guardar</button>
        </div>
    }
}

BosquesPaz/Views/Fotos/FotosVisualizacion.cshtml
@model IEnumerable<BosquesPaz.Models.FotosBosques>
<style>
    .mySlides {
        display: none;
    }

    .demo {
        cursor: pointer;
    }
</style>

@{
    int item = 1;
}
@if (Model.Count() > 0)
{
<div class="w3-content" style="max-width:800px">
   
        @foreach (var foto in Model)
        {
            <img src="/Multimedia/Imagen?img=@foto.Url.Split('\\').LastOrDefault()" style="max-width:100%; max-height:400px;margin:auto;">
            break;
        }
    
    @* <div class="w3-row-padding w3-section">
            @foreach (var foto in Model)
            {
                <div class="w3-col s1">
                    <img class="demo w3-opacity w3-hover-opacity-off" src="/Multimedia/Imagen?img=@foto.Url.Split('\\').LastOrDefault()" style="width:100%; margin:auto;" onclick="currentDiv(@item)">
                </div>
                item++;
            }
        </div>*@
</div>

    <script>
        var slideIndex = 1;
        showDivs(slideIndex);

        function plusDivs(n) {
            showDivs(slideIndex += n);
        }

        function currentDiv(n) {
            showDivs(slideIndex = n);
        }

        function showDivs(n) {
            var i;
            var x = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("demo");
            if (n > x.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = x.length }
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
            }
            x[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " w3-opacity-off";
        }
    </script>
}
@if (Model.Count() == 0)
{
    <div class="w3-content" style="max-width:400px">
        <img src="/Content/Imagenes/Bosque.jpg" style="max-width:100%; max-height:400px;margin:auto;">      
    </div>
}

BosquesPaz/Views/Fotos/FotosVisualizacionProductosServicios.cshtml
@model IEnumerable<BosquesPaz.Models.FotosProductosServicios>
<style>
    .mySlides {
        display: none;
    }

    .demo {
        cursor: pointer;
    }
</style>

@{
    int item = 1;
}
@if (Model.Count() > 0)
{
    <div class="w3-content">

        
            @foreach (var foto in Model)
            {
               
                    <img class="demo w3-opacity w3-hover-opacity-off" src="/Multimedia/Imagen?img=@foto.Url.Split('\\').LastOrDefault()" style="width:100%; margin:auto;" onclick="currentDiv(@item)">

                break;
            }
       
    </div>

    <script>
        var slideIndex = 1;
        showDivs(slideIndex);

        function plusDivs(n) {
            showDivs(slideIndex += n);
        }

        function currentDiv(n) {
            showDivs(slideIndex = n);
        }

        function showDivs(n) {
            var i;
            var x = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("demo");
            if (n > x.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = x.length }
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
            }
            x[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " w3-opacity-off";
        }
    </script>
}
@if (Model.Count() == 0)
{
    <div class="w3-content" style="max-width:800px">
        <img src="~/Content/Imagenes/productoServicio.png">
    </div>
}

BosquesPaz/Views/Fotos/FotosVisualizacionindividuosEspecies.cshtml
@model IEnumerable<BosquesPaz.Models.FotosIndividuosEspecies>
<style>
    .mySlides {
        display: none;
    }

    .demo {
        cursor: pointer;
    }
</style>

@{
    int item = 1;
}
@if (Model.Count() > 0)
{
    <div class="w3-content" style="max-width:800px">
    
     
            @foreach (var foto in Model)
            {
               
                    <img class="demo w3-opacity w3-hover-opacity-off" src="/Multimedia/Imagen?img=@foto.Url.Split('\\').LastOrDefault()" style="width:100%; margin:auto;" onclick="currentDiv(@item)">
              
                break;
            }
     
    </div>

    <script>
        var slideIndex = 1;
        showDivs(slideIndex);

        function plusDivs(n) {
            showDivs(slideIndex += n);
        }

        function currentDiv(n) {
            showDivs(slideIndex = n);
        }

        function showDivs(n) {
            var i;
            var x = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("demo");
            if (n > x.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = x.length }
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
            }
            x[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " w3-opacity-off";
        }
    </script>
}
@if (Model.Count() == 0)
{
    <div class="w3-content" style="max-width:800px">
        <img src="~/Content/Imagenes/especiesRecuperadas.png" style="max-width:100%; max-height:400px;margin:auto;">
    </div>
}