BosquesPaz/Controllers/IndividuoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BosquesPaz.Models;
using BosquesPaz.Services;
using BosquesPaz.Helpers;
using PagedList.Mvc;
using System.Web.Routing;
using BosquesPaz.ServiceReferenceFuncionarios;

namespace BosquesPaz.Controllers
{
    /// <summary>
    /// Clase que responde a las acciones que solicitan las peticiones de entrada y salida. 
    /// </summary>
    /// <remarks>
    /// <h3>Calidad</h3>
    /// </hr>
    /// <b>Requerimiento: Help Desk</b></br>
    /// <b>Version: 1</b></br>
    /// <b>Autor: Grupo Cubo Ltda.</b></br>
    /// <b>Fecha: 19/12/2017<b></br>
    /// <b>Descripcion:</b> Funciona para visualizar las vistas de individuos/especies, realizar peticiones a la capa de servicios y ejecutar acciones.
    /// </remarks>
    public class IndividuoController : Controller
    {
        /// <summary>
        /// Propiedad que instancia la clase CombosService
        /// </summary>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Propiedad que instancia el servicio CombosService, para enviar peticiones y recibir el resultado.
        /// </remarks>
        private CombosService service { get { return new CombosService(); } }

        /// <summary>
        /// Propiedad que instancia la clase IndividuosService
        /// </summary>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Propiedad que instancia el servicio IndividuosService, para enviar peticiones y recibir el resultado.
        /// </remarks>
        private IndividuosService serviceIndividuo { get { return new IndividuosService(); } }

        /// <summary>
        /// Accion que realiza la carga de la vista index de individuos/especies
        /// </summary>
        /// <param name="id">Identificador del bosque</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Accion que realiza el retorno de la vista parcial index de individuos/especies segun el numero de identificador que ingrese.
        /// </remarks>
        // GET: Individuo
        public ActionResult Index(int id)
        {
            ViewBag.idBosque = id;
            return PartialView();
        }

        /// <summary>
        /// Accion que realiza la carga de la vista detalles de individuo/especie
        /// </summary>
        /// <param name="id">Identificador del individuo/especie</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Accion que realiza el retorno de la vista parcial detalle de individuos/especies segun el numero de identificador que ingrese.
        /// </remarks>
        // GET: Bosque/Details/5
        public ActionResult Details(int id)
        {
            var model = serviceIndividuo.ObtenerIndividuosEspecies(id);
            return PartialView(model);
        }

        /// <summary>
        /// Accion que realiza la carga de la vista crear de individuo/especie
        /// </summary>
        /// <param name="id">Identificador del bosque</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Accion que realiza el retorno de la vista parcial crear de individuos/especies.
        /// </remarks>
        public ActionResult Create(int id)
        {
            ViewBag.TiposIndividuosEspecies = service.ObtenerTiposIndividuosEspecies();
            ViewBag.UnidadesIndividuosEspecies = service.ObtenerUnidadesIndividuosEspecies();
            var model = new IndividuosEspecies();
            model.Id_Bosque = id;
            return PartialView(model);
        }

        /// <summary>
        /// Accion que guarda los datos de la vista crear de individuo/especie
        /// </summary>
        /// <param name="viewModel">Instancia de IndividuosEspecies</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Recibe una instancia de IndividuosEspecies y la envia a la clase de servicio, y retorna redireccion de accion con el identificador de la instancia como parametro.
        /// </remarks>
        [HttpPost]
        public ActionResult Create(IndividuosEspecies viewModel)
        {
            var info = Session["infoUsuario"] as EntidadInfoUsuario;

            string ipAddress = string.Empty;
            if (!string.IsNullOrEmpty(Request.ServerVariables[""]))
            {

                ipAddress = Request.ServerVariables["HTTP_X_FORWARDED_FOR"];
            }
            else
            {
                ipAddress = Request.ServerVariables["REMOTE_ADDR"];
            }

            try
            {
                viewModel.Aud_User = info.Usuario;
                viewModel.Aud_Origen = ipAddress;
                if (ModelState.IsValid)
                {
                    viewModel = serviceIndividuo.GuardarIndividuo(viewModel);
                    return RedirectToAction("Details", new { id = viewModel.Id_IndividuoEspecie });
                }
                ViewBag.TiposIndividuosEspecies = service.ObtenerTiposIndividuosEspecies();
                ViewBag.UnidadesIndividuosEspecies = service.ObtenerUnidadesIndividuosEspecies();
                return PartialView(viewModel);
            }
            catch
            {
                ViewBag.TiposIndividuosEspecies = service.ObtenerTiposIndividuosEspecies();
                ViewBag.UnidadesIndividuosEspecies = service.ObtenerUnidadesIndividuosEspecies();
                return PartialView(viewModel);
            }
        }

        /// <summary>
        /// Método que serializa la informacion en formato JSON
        /// </summary>
        /// <param name="id">Identificador del bosque</param>
        /// <param name="agrid">Parametors de la grilla</param>
        /// <returns>Retorna JsonResult</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Realiza la serializacion de los datos recibidos a formato JSON, para cargar la grilla de individuos/especies segun el numero de identificador que ingrese.
        /// </remarks>
        public JsonResult CargarGrilla(AnexGRID agrid, int id)
        {
            return Json(DataSourceGrilla(agrid, id), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Método que retorna AnexGRIDResponde, segun sus parametros.
        /// </summary>
        /// <param name="id">Identificador del bosque</param>
        /// <param name="agrid">Parametors de la grilla</param>
        /// <returns>Retorna AnexGRIDResponde</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Método que permite obtener los datos de IndividuosEspecies, y organizarlos con el proposito de retornarlos a una grilla.
        /// </remarks>
        [NonAction]
        public AnexGRIDResponde DataSourceGrilla(AnexGRID agrid, int id)
        {
            try
            {
                IEnumerable<IndividuosEspecies> registros = new List<IndividuosEspecies>();
                IDictionary<string, string> filtros = new Dictionary<string, string>();
                if (agrid.filtros != null)
                    foreach (var filtro in agrid.filtros)
                    {
                        filtros.Add(filtro.columna, filtro.valor);
                    }

                registros = serviceIndividuo.ObtenerIndividuosEspeciesBosques(agrid.pagina, agrid.limite, agrid.columna, filtros, agrid.columna_orden != "DESC", id);

                if (registros != null)
                {
                    agrid.Inicializar();
                    int cantidadRegistros = serviceIndividuo.CantidadRegistros;
                    agrid.SetData(registros, cantidadRegistros);
                }
                return agrid.responde();
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }

        /// <summary>
        /// Accion que realiza la carga de la vista editar de individuo/especie
        /// </summary>
        /// <param name="id">Identificador del individuo/especie</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>

BosquesPaz/Views/Individuo/create.cshtml
@model BosquesPaz.Models.IndividuosEspecies

@using (Ajax.BeginForm("Create", "Individuo", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "IndividuosContainer" }))
{
    <div class="form-group">
        <br />
        <br />
        @Html.HiddenFor(model => model.Id_Bosque)
        <div class="row">
            <div class="col-md-3">
                <label>Tipo:</label>
            </div>
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.Id_TipoIndividuoEspecie, new SelectList(ViewBag.TiposIndividuosEspecies, "Id_TipoIndividuoEspecie", "Nombre"), "SELECCIONE...", new { @class = "chosen-select-single" })
                @Html.ValidationMessageFor(model => model.Id_TipoIndividuoEspecie, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <label>Nombre:</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <label>Descripción:</label>
            </div>
            <div class="col-md-8">
                @Html.TextAreaFor(model => model.Descripcion, 5, 100, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <label>Cantidad estimada:</label>
            </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <label>Unidad:</label>
            </div>
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.Id_UnidadIndividuoEspecie, new SelectList(ViewBag.UnidadesIndividuosEspecies, "Id_UnidadIndividuoEspecie", "Nombre"), "SELECCIONE...", new { @class = "chosen-select-single" })
                @Html.ValidationMessageFor(model => model.Id_UnidadIndividuoEspecie, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-xs-9"></div>
            <div class="col-xs-3">
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-default" />
                    <input id="btnListadoIndividuoEspecie" type="button" onclick="cargarListaIndividuos(@Model.Id_Bosque)" value="Volver" class="btn btn-form" />
                </div>
            </div>
        </div>
    </div>
}

<script>

    $(".chosen-select-single").chosen({
        no_results_text: "Sin Resultado",
        width: "100%",
        search_contains: true,
        placeholder_text_single: 'SELECCIONE...',
        display_selected_options: false
    });
</script>

BosquesPaz/Views/Individuo/details.cshtml
@model BosquesPaz.Models.IndividuosEspecies
@using BosquesPaz.Helpers
@using BosquesPaz.ServiceReferenceFuncionarios

@{
    ///Almacena la cadena de caracteres de la direccion url de el detalle de individuos/especies
    string url = "?m=Bosques&id=" + Model.Id_Bosque + "&mb=Individuos&mbid=" + Model.Id_IndividuoEspecie;
}

<div class="form-group">
    <br />
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Tipo:</label>
        </div>
        <div class="col-md-8">
            @Html.DisplayFor(model => model.TiposIndividuosEspecies.Nombre, new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Nombre:</label>
        </div>
        <div class="col-md-8">
            @Html.DisplayFor(model => model.Nombre, new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Descripción:</label>
        </div>
        <div class="col-md-8">
            @Html.DisplayFor(model => model.Descripcion, new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Cantidad:</label>
        </div>
        <div class="col-md-8">
            @Html.DisplayFor(model => model.Cantidad, new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Unidad:</label>
        </div>
        <div class="col-md-8">
            @Html.DisplayFor(model => model.UnidadesIndividuosEspecies.Nombre, new { @class = "form-control" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Imagenes:</label>
        </div>
        <div class="col-md-8 inner-addon right-addon">
            <span class="glyphicon glyphicon-picture" />
            <input id="btnImagenesIndividuosEspecies" type="button" onclick="LoadPhotosIndividuosEspecies(@Model.Id_IndividuoEspecie)" value="Imagenes" class="btn btn-form" />
        </div>
    </div>
    <br />
    <br />
    <div class="row">
        <div class="w3-container">
            <div class="w3-panel w3-border w3-round w3-border-gray">
                <div class="w3-row">
                    <a href="javascript:void(0)" onclick="openBosques(event, 'Historial');">
                        <div class="w3-third tablink bosquetablink w3-bottombar w3-hover-light-grey w3-padding w3-border-blue" style="width:20%;">Historial</div>
                    </a>
                </div>
                <div id="Historial" class="w3-container bosque">
                    <div id="HistorialIndividuosContainer" style="width:100%">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <br />
    <div class="row">
        <div class="col-xs-8"></div>
        <div class="col-xs-4">
            <div class="form-group">
                <div id="fb-link" class="fb-share-button" data-href="https://gcl.westeurope.cloudapp.azure.com:8199/@url" data-layout="button" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fgcl.westeurope.cloudapp.azure.com%3A8199%2F&amp;src=sdkpreparse">Compartir</a></div>
                @{
                    ///Realiza la instancia de la clase infraestructura para verificar los permisos del usuario
                    var infraestructura = new Infraestructura();
                    EntidadInfoUsuario info = null;
                    if (Session["infoUsuario"] != null)
                    {
                        info = Session["infoUsuario"] as EntidadInfoUsuario;
                    }
                }
                @if (infraestructura.PermisoUsuario(info, "Editar", "IndividuosEspecies"))
                {
                    <input id="btnListadoIndividuosEspecies" type="button" onclick="EditarIndividuoEspecie(@Model.Id_IndividuoEspecie)" value="Editar" class="btn btn-form" />
                }
                <input id="btnListadoIndividuosEspecies" type="button" onclick="cargarListaIndividuos(@Model.Id_Bosque)" value="Volver" class="btn btn-form" />
            </div>
        </div>
    </div>
</div>
<div id="fb-root"></div>
<script>
    cargarListaProductoServicio(@Model.Id_Bosque);

    FB = null;
    (function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        //if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.11';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<script>
    cargarListaAdministradorIndividuosHistorial(@Model.Id_IndividuoEspecie);
</script>

BosquesPaz/Views/Individuo/edit.cshtml
@model BosquesPaz.Models.IndividuosEspecies

@using (Ajax.BeginForm("Edit", "Individuo", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "IndividuosContainer" }))
{
<div class="form-group">
    <br />
    <br />
    @Html.HiddenFor(model => model.Id_Bosque)
    @Html.HiddenFor(model => model.Id_IndividuoEspecie)
    <div class="row">
        <div class="col-md-3">
            <label>Tipo:</label>
        </div>
        <div class="col-md-6">
            @Html.DropDownListFor(model => model.Id_TipoIndividuoEspecie, new SelectList(ViewBag.TiposIndividuosEspecies, "Id_TipoIndividuoEspecie", "Nombre"), "SELECCIONE...", new { @class = "chosen-select-single" })
            @Html.ValidationMessageFor(model => model.Id_TipoIndividuoEspecie, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Nombre:</label>
        </div>
        <div class="col-md-8">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Descripción:</label>
        </div>
        <div class="col-md-8">
            @Html.TextAreaFor(model => model.Descripcion, 5, 100, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Cantidad estimada:</label>
        </div>
        <div class="col-md-8">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-3">
            <label>Unidad:</label>
        </div>
        <div class="col-md-6">
            @Html.DropDownListFor(model => model.Id_UnidadIndividuoEspecie, new SelectList(ViewBag.UnidadesIndividuosEspecies, "Id_UnidadIndividuoEspecie", "Nombre"), "SELECCIONE...", new { @class = "chosen-select-single" })
            @Html.ValidationMessageFor(model => model.Id_UnidadIndividuoEspecie, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="col-xs-9"></div>
        <div class="col-xs-3">
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-default" />
                <input id="btnDetalleIndividuoEspecie" type="button" onclick="DetalleIndividuoEspecie(@Model.Id_IndividuoEspecie)" value="Volver" class="btn btn-form" />
            </div>
        </div>
    </div>
</div>
}

<script>

    $(".chosen-select-single").chosen({
        no_results_text: "Sin Resultado",
        width: "100%",
        search_contains: true,
        placeholder_text_single: 'SELECCIONE...',
        display_selected_options: false
    });
</script>

BosquesPaz/Views/Individuo/index.cshtml
@using BosquesPaz.Helpers
@using BosquesPaz.ServiceReferenceFuncionarios
<br />
<br />
@{ 
    ///Realiza la instancia de la clase infraestructura para verificar los permisos del usuario
    var infraestructura = new Infraestructura();
    EntidadInfoUsuario info = null;
    if (Session["infoUsuario"] != null)
    {
        info = Session["infoUsuario"] as EntidadInfoUsuario;
    }
}
@if (infraestructura.PermisoUsuario(info, "Crear", "IndividuosEspecies"))
{
    <input id="btnCrearIndividuoEspecie" type="button" onclick="CrearIndividuoEspecie(@ViewBag.idBosque);" value="Nuevo" class="btn btn-new" />
}


<br />
<br />
<div class="table-responsive">
    <div id="IndexIndividuoEspecie"></div>
</div>
<br />


<script>
    $(function () {
        var DataIndividuoEspecie = {
            class: 'table-striped table-bordered table-responsive',
            columnas: [
                {
                    leyenda: 'Detalle', style: 'width:15px;', class: 'text-center'
                },
                {
                    leyenda: 'Tipo', style: 'width:20%;', class: 'text-center', columna: 'TipoInidividuoEspecie'
                },
                {
                    leyenda: 'Nombre', style: 'width:20%;', class: 'text-center', columna: 'Nombre'
                },
                {
                    leyenda: 'Descripción', style: 'width:20%;', class: 'text-center', columna: 'Descripcion'
                },
                {
                    leyenda: 'Cantidad', style: 'width:20%;', class: 'text-center', columna: 'Cantidad'
                },
                {
                    leyenda: 'Unidad', style: 'widht:20%', class: 'text-center', columna: 'UnidadIndividuoEspecie' 
                },
                {
                    leyenda: 'Imagenes', style: 'width:20%;', class: 'text-center'
                },
            ],
            modelo: [
                 {
                     formato: function (tr, obj, valor) {
                         return anexGrid_boton({
                             class: 'btn btn-default btn-DetalleIndividuoEspecie',
                             contenido: '<span class="glyphicon glyphicon-edit" />',
                             value: obj.Id_IndividuoEspecie
                         });
                     }
                 },
                 {
                     propiedad: 'TipoInidividuoEspecie', style: 'text-align: justify;'
                 },
                 {
                     propiedad: 'Nombre', style: 'text-align: justify;'
                 },
                 {
                     propiedad: 'Descripcion', style: 'text-align: justify;'
                 },
                 {
                     propiedad: 'Cantidad', style: 'text-align: justify;'
                 },
                 {
                     propiedad: 'UnidadIndividuoEspecie', style: 'text-align: justify;'
                 },
                 {
                     formato: function (tr, obj, valor) {
                         return anexGrid_boton({
                             class: 'btn btn-default btn-ImagenesIndividuoEspecie',
                             contenido: '<span class="glyphicon glyphicon-picture" />',
                             value: obj.Id_IndividuoEspecie
                         });
                     }
                 }
            ],
            url: '@Url.Action("CargarGrilla", "Individuo")' + '/' + @ViewBag.idBosque,
            limite: [5, 10, 20],
            columna: 'Id_IndividuoEspecie',
            paginable: true,
            filtrable: true,
            columna_orden: 'DESC'
        };
        var GridRecursosBosques = $("#IndexIndividuoEspecie").anexGrid(DataIndividuoEspecie);

        GridRecursosBosques.tabla().on('click', '.btn-DetalleIndividuoEspecie', function () {
            DetalleIndividuoEspecie(this.value);
        });
        GridRecursosBosques.tabla().on('click', '.btn-ImagenesIndividuoEspecie', function () {
            LoadPhotosIndividuosEspecies(this.value);
        });
    });
</script>