BosquesPaz/Controllers/ProductoServicioBosquesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BosquesPaz.Models;
using BosquesPaz.Services;
using BosquesPaz.Helpers;
using System.IO;

namespace BosquesPaz.Controllers
{
    /// <summary>
    /// Clase que responde a las acciones que solicitan las peticiones de entrada y salida. 
    /// </summary>
    /// <remarks>
    /// <h3>Calidad</h3>
    /// </hr>
    /// <b>Requerimiento: Help Desk</b></br>
    /// <b>Version: 1</b></br>
    /// <b>Autor: Grupo Cubo Ltda.</b></br>
    /// <b>Fecha: 19/12/2017<b></br>
    /// <b>Descripcion:</b> Funciona para visualizar las vistas de productos/servicios, realizar peticiones a la capa de servicios y ejecutar acciones.
    /// </remarks>
    public class ProductoServicioBosquesController : Controller
    {
        /// <summary>
        /// Propiedad que instancia la clase ProductosServiciosService
        /// </summary>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Propiedad que instancia el servicio ProductosServiciosService, para enviar peticiones y recibir el resultado.
        /// </remarks>
        private ProductosServiciosService servicio { get{ return new ProductosServiciosService(); } }
        private TiposProductosServiciosService servicioTiposProductosServicios { get { return new TiposProductosServiciosService(); } }


        /// <summary>
        /// Accion que realiza la carga de la vista index de producto/servicio
        /// </summary>
        /// <param name="id">Identificador del bosque</param>
        /// <returns>Retorna vista parcial</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Accion que realiza el retorno de la vista parcial index de producto/servicio segun el numero de identificador que ingrese.
        /// </remarks>
        // GET: ProductoServicioBosques
        public ActionResult Index(int id)
        {
            ProductosServicios ProductosServicios = servicio.ObtenerProductosServicios(id);

            ViewBag.Id =id ;
            ViewBag.Tipo = servicioTiposProductosServicios.ObtenerNombreTipoProductoServicioPorId(ProductosServicios.Id_TipoProductoServicio);
            ViewBag.Nombre = ProductosServicios.Nombre;
            ViewBag.Descripcion = ProductosServicios.Descripcion;
            ViewBag.Precio = ProductosServicios.Precio;
            ViewBag.NombreBosque = ProductosServicios.NombreBosque;
            ViewBag.Departamento = ProductosServicios.Departamento;
            ViewBag.Municipio = ProductosServicios.Municipio;

            return PartialView();
        }

        /// <summary>
        /// Método que serializa la informacion en formato JSON
        /// </summary>
        /// <param name="agrid">Parametors de la grilla</param>
        /// <returns>Retorna JsonResult</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Realiza la serializacion de los datos recibidos a formato JSON, para cargar la grilla de productos/servicios.
        /// </remarks>
        public JsonResult CargarGrilla(AnexGRID agrid)
        {
            return Json(DataSourceGrilla(agrid), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Método que retorna AnexGRIDResponde, segun sus parametros.
        /// </summary>
        /// <param name="agrid">Parametors de la grilla</param>
        /// <returns>Retorna AnexGRIDResponde</returns>
        /// <remarks>
        /// <h3>Calidad</h3>
        /// </hr>
        /// <b>Requerimiento:</b> Help Desk</br>
        /// <b>Version:</b> 1</br>
        /// <b>Autor:</b> Grupo Cubo Ltda.</br>
        /// <b>Fecha:</b> 19/12/2017</br>
        /// <b>Descripcion:</b> Método que permite obtener los datos de ProductosServicios, y organizarlos con el proposito de retornarlos a una grilla.
        /// </remarks>
        [NonAction]
        public AnexGRIDResponde DataSourceGrilla(AnexGRID agrid)
        {
            try
            {
                IEnumerable<ProductosServicios> registros = new List<ProductosServicios>();
                IDictionary<string, string> filtros = new Dictionary<string, string>();
                if (agrid.filtros != null)
                    foreach (var filtro in agrid.filtros)
                    {
                        filtros.Add(filtro.columna, filtro.valor);
                    }

                registros = servicio.ObtenerProductosServiciosBosques(agrid.pagina, agrid.limite, agrid.columna, filtros, agrid.columna_orden != "DESC");

                if (registros != null)
                {
                    agrid.Inicializar();
                    int cantidadRegistros = servicio.CantidadRegistros;
                    agrid.SetData(registros, cantidadRegistros);
                }
                return agrid.responde();
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }
    }
}

BosquesPaz/Views/ProductoServicioBosques/index.cshtml
@{
Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <title>EcoTech - Producto</title>
    <link rel="stylesheet" type="text/css" href="~/styles/product_styles.css">
    <link rel="stylesheet" type="text/css" href="~/styles/product_responsive.css">
</head>
<!-- Producto -->
<div class="single_product">
        <div class="container">
            <div class="row">
                <!-- Selected Image -->
                <div class="col-lg-5 order-lg-2 order-1">
                    <div class="image_selected">
                        <script>LoadPhotoProductoServicio(@ViewBag.Id);</script>
                        <div class='ps_@(@ViewBag.Id)'></div>
                    </div>
                </div>
                <!-- Description -->
                <div class="col-lg-5 order-3">
                    <div class="product_description">
                        <div class="product_category">@ViewBag.Tipo</div>
                        <div class="product_name">@ViewBag.Nombre</div>
                        <div class="rating_r rating_r_4 product_rating"><i></i><i></i><i></i><i></i><i></i></div>
                        <div class="product_text">
                            <p>@ViewBag.Descripcion</p>
                        </div>
                        <div class="product_price">Precio: $@ViewBag.Precio COP</div>
                             <!--   <div class="button_container">
                                    <button type="button" class="button cart_button">Contactar</button>
                                    <div class="product_fav"><i class="fas fa-heart"></i></div>
                                </div>-->
                    </div>
                </div>

            </div>
        </div>
</div>
<!-- Información detallada -->
<div class="viewed">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="viewed_title_container">
                        <h3 class="viewed_title">Información</h3>
                    </div>    
                    <br>
                    <p><b>Nombre Bosque:</b> @ViewBag.NombreBosque</p>                                
                    <p><b>Departamento:</b> @ViewBag.Departamento</p> 
                    <p><b>Municipio:</b> @ViewBag.Municipio</p> 
                </div>
            </div>
        </div>
</div>  

<script src="~/js/product_custom.js"></script>    

BosquesPaz/Views/ProductoServicioBosques/index_old.cshtml
@using (Ajax.BeginForm("Index", "ProductoServicioBosques", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "ProductosServiciosBosquesContainer" }))
{
    <br />
    <br />
    <div class="table-responsive">
        <div id="IndexProductosServiciosBosques"></div>
    </div>
    <script>
        var idBosque = 0;
        $(function () {
            var DataProductosServiciosBosques = {
                class: 'table-striped table-bordered table-responsive',
                columnas: [
                    {
                        leyenda: 'Detalle', style: 'width:15px;', class: 'text-center'
                    },
                    {
                        leyenda: 'Tipo', style: 'width:150px;', class: 'text-center', ordenable: true, columna: 'TipoProductoServicio'//, filtro: function () {
                    },
                    {
                        leyenda: 'Nombre', style: 'width:150px;', class: 'text-center', ordenable: true, columna: 'Nombre'
                    },
                    {
                        leyenda: 'Descripcion', style: 'width:20%;', class: 'text-center', columna: 'Descripcion'
                    },
                    {
                        leyenda: 'Imagen', style: 'width:20%;', class: 'text-center', columna: 'Foto'
                    },
                    {
                        leyenda: 'Precio', style: 'width:20%;', class: 'text-center', columna: 'Precio'
                    },
                    {
                        leyenda: 'Bosque', style: 'width:20%;', class: 'text-center', columna: 'NombreBosque'
                    },
                    {
                        leyenda: 'Departamento', style: 'width:20%;', class: 'text-center', columna: 'Departamento'
                    },
                    {
                        leyenda: 'Municipio', style: 'width:20%;', class: 'text-center', columna: 'Municipio'
                    },
                    {
                        leyenda: 'Fecha de modificacion', style: 'width:20%;', class: 'text-center', columna: 'FechaActualizacion'
                    },
                ],
                modelo: [
                     {
                        formato: function (tr, obj, valor) {
                            return anexGrid_boton({
                                class: 'btn btn-default btn-DetalleProductoServicio',
                                contenido: '<span class="glyphicon glyphicon-edit" />',
                                value: "?m=Bosques&id=" + obj.Id_Bosque + '&mb=Productos&mbid=' + obj.Id_ProductoServicio
                            });
                        }
                     },
                     {
                         propiedad: 'TipoProductoServicio', style: 'text-align: justify;'
                     },
                     {
                         propiedad: 'Nombre', style: 'text-align: justify;'
                     },
                     {
                         propiedad: 'Descripcion', style: 'text-align: justify;'
                     },
                     {
                         formato: function (tr, obj, valor) {
                             return anexGrid_boton({
                                 class: 'btn btn-default btn-ImagenesProductoServicio',
                                 contenido: '<span class="glyphicon glyphicon-picture" />',
                                 value: obj.Id_ProductoServicio
                             });
                         }
                     },
                     {
                         propiedad: 'Precio', style: 'text-align: justify;'
                     },
                     {
                         propiedad: 'NombreBosque', style: 'text-align: justify;'
                     },
                     {
                         propiedad: 'Departamento', style: 'text-align: justify;'
                     },
                     {
                         propiedad: 'Municipio', style: 'text-align: justify;'
                     },
                     {
                         propiedad: 'FechaActualizacion', style: 'text-align: justify;'
                     },
                ],
                url: '@Url.Action("CargarGrilla", "ProductoServicioBosques")',
                limite: [5, 10, 20],
                columna: 'Id_ProductoServicio',
                paginable: true,
                filtrable: true,
                columna_orden: 'DESC'
            };
            var GridProductosServiciosBosques = $("#IndexProductosServiciosBosques").anexGrid(DataProductosServiciosBosques);

            GridProductosServiciosBosques.tabla().on('click', '.btn-DetalleProductoServicio', function () {
                DetalleProductoServicioBosques(this.value);
            });
            GridProductosServiciosBosques.tabla().on('click', '.btn-ImagenesProductoServicio', function () {
                LoadPhotosProductosServicios(this.value);
            });
        });

        function DetalleProductoServicioBosques(cadena) {
            location.href = cadena;
        }
    </script>
}